final List<Map<String, String>> onboardingData = [
  {
    'title': 'Peluang Besar,\nSemua Ada di Sini',
    'description':
    'Layanan apapun, semua bisa kamu\nkerjain dari satu aplikasi.',
  },
  {
    'title': 'Pilih Sendiri Layanan,\nyang Mau Kamu Jalanin',
    'description':
    'Mau antar barang, bantu bersih rumah,\natau jasa lainnya. Kamu yang Tentuin.',
  },
  {
    'title': 'Ubah Waktu Luang\nJadi Lebih Cuan',
    'description':
    'Gabung jadi Agent, terima pesanan,\ndan hasilkan pendapatan kapanpun. ',
  },
  {
    'title': 'Dapat Order Cepat,\nBayaran Otomatis',
    'description':
    'Terima pesanan real-time.\nTanpa ribet, semuanya langsung jalan.',
  },
  {
    'title': 'Semua Aman dalam\nSatu Aplikasi',
    'description':
    'Satu aplikasi untuk kelola layanan,\npesanan, penghasilan, dan performa.',
  },
];

List<Map<String, dynamic>> countryDataList = [
  /// Prioritas Utama
  {"id": 1, "name": "Indonesia", "iso_code": "ID", "dial_code": "+62", "flag_emoji": "🇮🇩"},
  {"id": 2, "name": "Australia", "iso_code": "AU", "dial_code": "+61", "flag_emoji": "🇦🇺"},
  {"id": 3, "name": "Malaysia", "iso_code": "MY", "dial_code": "+60", "flag_emoji": "🇲🇾"},
  {"id": 4, "name": "Singapore", "iso_code": "SG", "dial_code": "+65", "flag_emoji": "🇸🇬"},

  {"id": 5, "name": "Afghanistan", "iso_code": "AF", "dial_code": "+93", "flag_emoji": "🇦🇫"},
  {"id": 6, "name": "Albania", "iso_code": "AL", "dial_code": "+355", "flag_emoji": "🇦🇱"},
  {"id": 7, "name": "Algeria", "iso_code": "DZ", "dial_code": "+213", "flag_emoji": "🇩🇿"},
  {"id": 8, "name": "Argentina", "iso_code": "AR", "dial_code": "+54", "flag_emoji": "🇦🇷"},
  {"id": 9, "name": "Austria", "iso_code": "AT", "dial_code": "+43", "flag_emoji": "🇦🇹"},
  {"id": 10, "name": "Bangladesh", "iso_code": "BD", "dial_code": "+880", "flag_emoji": "🇧🇩"},
  {"id": 11, "name": "Belgium", "iso_code": "BE", "dial_code": "+32", "flag_emoji": "🇧🇪"},
  {"id": 12, "name": "Brazil", "iso_code": "BR", "dial_code": "+55", "flag_emoji": "🇧🇷"},
  {"id": 13, "name": "Brunei", "iso_code": "BN", "dial_code": "+673", "flag_emoji": "🇧🇳"},
  {"id": 14, "name": "Bulgaria", "iso_code": "BG", "dial_code": "+359", "flag_emoji": "🇧🇬"},
  {"id": 15, "name": "Cambodia", "iso_code": "KH", "dial_code": "+855", "flag_emoji": "🇰🇭"},
  {"id": 16, "name": "Canada", "iso_code": "CA", "dial_code": "+1", "flag_emoji": "🇨🇦"},
  {"id": 17, "name": "Chile", "iso_code": "CL", "dial_code": "+56", "flag_emoji": "🇨🇱"},
  {"id": 18, "name": "China", "iso_code": "CN", "dial_code": "+86", "flag_emoji": "🇨🇳"},
  {"id": 19, "name": "Colombia", "iso_code": "CO", "dial_code": "+57", "flag_emoji": "🇨🇴"},
  {"id": 20, "name": "Croatia", "iso_code": "HR", "dial_code": "+385", "flag_emoji": "🇭🇷"},
  {"id": 21, "name": "Czech Republic", "iso_code": "CZ", "dial_code": "+420", "flag_emoji": "🇨🇿"},
  {"id": 22, "name": "Denmark", "iso_code": "DK", "dial_code": "+45", "flag_emoji": "🇩🇰"},
  {"id": 23, "name": "Egypt", "iso_code": "EG", "dial_code": "+20", "flag_emoji": "🇪🇬"},
  {"id": 24, "name": "Finland", "iso_code": "FI", "dial_code": "+358", "flag_emoji": "🇫🇮"},
  {"id": 25, "name": "France", "iso_code": "FR", "dial_code": "+33", "flag_emoji": "🇫🇷"},
  {"id": 26, "name": "Germany", "iso_code": "DE", "dial_code": "+49", "flag_emoji": "🇩🇪"},
  {"id": 27, "name": "Ghana", "iso_code": "GH", "dial_code": "+233", "flag_emoji": "🇬🇭"},
  {"id": 28, "name": "Greece", "iso_code": "GR", "dial_code": "+30", "flag_emoji": "🇬🇷"},
  {"id": 29, "name": "Hong Kong", "iso_code": "HK", "dial_code": "+852", "flag_emoji": "🇭🇰"},
  {"id": 30, "name": "Hungary", "iso_code": "HU", "dial_code": "+36", "flag_emoji": "🇭🇺"},
  {"id": 31, "name": "Iceland", "iso_code": "IS", "dial_code": "+354", "flag_emoji": "🇮🇸"},
  {"id": 32, "name": "India", "iso_code": "IN", "dial_code": "+91", "flag_emoji": "🇮🇳"},
  {"id": 33, "name": "Iran", "iso_code": "IR", "dial_code": "+98", "flag_emoji": "🇮🇷"},
  {"id": 34, "name": "Iraq", "iso_code": "IQ", "dial_code": "+964", "flag_emoji": "🇮🇶"},
  {"id": 35, "name": "Ireland", "iso_code": "IE", "dial_code": "+353", "flag_emoji": "🇮🇪"},
  {"id": 36, "name": "Israel", "iso_code": "IL", "dial_code": "+972", "flag_emoji": "🇮🇱"},
  {"id": 37, "name": "Italy", "iso_code": "IT", "dial_code": "+39", "flag_emoji": "🇮🇹"},
  {"id": 38, "name": "Japan", "iso_code": "JP", "dial_code": "+81", "flag_emoji": "🇯🇵"},
  {"id": 39, "name": "Jordan", "iso_code": "JO", "dial_code": "+962", "flag_emoji": "🇯🇴"},
  {"id": 40, "name": "Kazakhstan", "iso_code": "KZ", "dial_code": "+7", "flag_emoji": "🇰🇿"},
  {"id": 41, "name": "Kenya", "iso_code": "KE", "dial_code": "+254", "flag_emoji": "🇰🇪"},
  {"id": 42, "name": "Kuwait", "iso_code": "KW", "dial_code": "+965", "flag_emoji": "🇰🇼"},
  {"id": 43, "name": "Laos", "iso_code": "LA", "dial_code": "+856", "flag_emoji": "🇱🇦"},
  {"id": 44, "name": "Lebanon", "iso_code": "LB", "dial_code": "+961", "flag_emoji": "🇱🇧"},
  {"id": 45, "name": "Luxembourg", "iso_code": "LU", "dial_code": "+352", "flag_emoji": "🇱🇺"},
  {"id": 46, "name": "Macao", "iso_code": "MO", "dial_code": "+853", "flag_emoji": "🇲🇴"},
  {"id": 47, "name": "Mexico", "iso_code": "MX", "dial_code": "+52", "flag_emoji": "🇲🇽"},
  {"id": 48, "name": "Mongolia", "iso_code": "MN", "dial_code": "+976", "flag_emoji": "🇲🇳"},
  {"id": 49, "name": "Morocco", "iso_code": "MA", "dial_code": "+212", "flag_emoji": "🇲🇦"},
  {"id": 50, "name": "Myanmar", "iso_code": "MM", "dial_code": "+95", "flag_emoji": "🇲🇲"},
  {"id": 51, "name": "Nepal", "iso_code": "NP", "dial_code": "+977", "flag_emoji": "🇳🇵"},
  {"id": 52, "name": "Netherlands", "iso_code": "NL", "dial_code": "+31", "flag_emoji": "🇳🇱"},
  {"id": 53, "name": "New Zealand", "iso_code": "NZ", "dial_code": "+64", "flag_emoji": "🇳🇿"},
  {"id": 54, "name": "Nigeria", "iso_code": "NG", "dial_code": "+234", "flag_emoji": "🇳🇬"},
  {"id": 55, "name": "North Korea", "iso_code": "KP", "dial_code": "+850", "flag_emoji": "🇰🇵"},
  {"id": 56, "name": "Norway", "iso_code": "NO", "dial_code": "+47", "flag_emoji": "🇳🇴"},
  {"id": 57, "name": "Oman", "iso_code": "OM", "dial_code": "+968", "flag_emoji": "🇴🇲"},
  {"id": 58, "name": "Pakistan", "iso_code": "PK", "dial_code": "+92", "flag_emoji": "🇵🇰"},
  {"id": 59, "name": "Palestine", "iso_code": "PS", "dial_code": "+970", "flag_emoji": "🇵🇸"},
  {"id": 60, "name": "Peru", "iso_code": "PE", "dial_code": "+51", "flag_emoji": "🇵🇪"},
  {"id": 61, "name": "Philippines", "iso_code": "PH", "dial_code": "+63", "flag_emoji": "🇵🇭"},
  {"id": 62, "name": "Poland", "iso_code": "PL", "dial_code": "+48", "flag_emoji": "🇵🇱"},
  {"id": 63, "name": "Portugal", "iso_code": "PT", "dial_code": "+351", "flag_emoji": "🇵🇹"},
  {"id": 64, "name": "Qatar", "iso_code": "QA", "dial_code": "+974", "flag_emoji": "🇶🇦"},
  {"id": 65, "name": "Romania", "iso_code": "RO", "dial_code": "+40", "flag_emoji": "🇷🇴"},
  {"id": 66, "name": "Russia", "iso_code": "RU", "dial_code": "+7", "flag_emoji": "🇷🇺"},
  {"id": 67, "name": "Saudi Arabia", "iso_code": "SA", "dial_code": "+966", "flag_emoji": "🇸🇦"},
  {"id": 68, "name": "South Africa", "iso_code": "ZA", "dial_code": "+27", "flag_emoji": "🇿🇦"},
  {"id": 69, "name": "South Korea", "iso_code": "KR", "dial_code": "+82", "flag_emoji": "🇰🇷"},
  {"id": 70, "name": "Spain", "iso_code": "ES", "dial_code": "+34", "flag_emoji": "🇪🇸"},
  {"id": 71, "name": "Sri Lanka", "iso_code": "LK", "dial_code": "+94", "flag_emoji": "🇱🇰"},
  {"id": 72, "name": "Sweden", "iso_code": "SE", "dial_code": "+46", "flag_emoji": "🇸🇪"},
  {"id": 73, "name": "Switzerland", "iso_code": "CH", "dial_code": "+41", "flag_emoji": "🇨🇭"},
  {"id": 74, "name": "Syria", "iso_code": "SY", "dial_code": "+963", "flag_emoji": "🇸🇾"},
  {"id": 75, "name": "Taiwan", "iso_code": "TW", "dial_code": "+886", "flag_emoji": "🇹🇼"},
  {"id": 76, "name": "Thailand", "iso_code": "TH", "dial_code": "+66", "flag_emoji": "🇹🇭"},
  {"id": 77, "name": "Turkey", "iso_code": "TR", "dial_code": "+90", "flag_emoji": "🇹🇷"},
  {"id": 78, "name": "Ukraine", "iso_code": "UA", "dial_code": "+380", "flag_emoji": "🇺🇦"},
  {"id": 79, "name": "United Arab Emirates", "iso_code": "AE", "dial_code": "+971", "flag_emoji": "🇦🇪"},
  {"id": 80, "name": "United Kingdom", "iso_code": "GB", "dial_code": "+44", "flag_emoji": "🇬🇧"},
  {"id": 81, "name": "United States", "iso_code": "US", "dial_code": "+1", "flag_emoji": "🇺🇸"},
  {"id": 82, "name": "Uruguay", "iso_code": "UY", "dial_code": "+598", "flag_emoji": "🇺🇾"},
  {"id": 83, "name": "Uzbekistan", "iso_code": "UZ", "dial_code": "+998", "flag_emoji": "🇺🇿"},
  {"id": 84, "name": "Venezuela", "iso_code": "VE", "dial_code": "+58", "flag_emoji": "🇻🇪"},
  {"id": 85, "name": "Vietnam", "iso_code": "VN", "dial_code": "+84", "flag_emoji": "🇻🇳"},
  {"id": 86, "name": "Yemen", "iso_code": "YE", "dial_code": "+967", "flag_emoji": "🇾🇪"},
];